# Generated by Django 3.2.4 on 2021-07-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ab_date_action',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='agency_bank',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
