# Generated by Django 3.2.4 on 2021-08-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_groupmemberinfo_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmemberinfo',
            name='family_on_hcdti_group',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmemberinfo',
            name='member_owning_mfi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
