# Generated by Django 3.2.4 on 2021-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210613_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('otp_code', models.TextField(null=True)),
                ('dt_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reset_otp',
            },
        ),
    ]
