# Generated by Django 3.2.4 on 2021-06-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_resetotp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResetOtp',
            new_name='Otp',
        ),
        migrations.AlterModelTable(
            name='otp',
            table='otp',
        ),
    ]
