# Generated by Django 3.2.4 on 2021-07-20 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_loanapplication_agency_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='agency_bank',
            new_name='agency_bank_approve',
        ),
        migrations.CreateModel(
            name='ApprovedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('form_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('loan_amt', models.FloatField(blank=True, null=True)),
                ('customer_bank', models.TextField(blank=True, null=True)),
                ('customer_acct_no', models.TextField(blank=True, null=True)),
                ('disbursed', models.CharField(default='PENDING', max_length=100)),
                ('date_disbursed', models.DateTimeField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.loanapplication')),
            ],
            options={
                'db_table': 'approved_loan',
            },
        ),
    ]
