# Generated by Django 3.2.4 on 2021-08-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210801_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmemberinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
