# Generated by Django 3.2.4 on 2021-07-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210616_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, null=True)),
                ('group_name', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_id', models.TextField(null=True)),
                ('member_name', models.TextField(null=True)),
                ('mobile_number', models.TextField(null=True)),
                ('is_leader', models.BooleanField(null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.groups')),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
    ]
