# Generated by Django 3.2.4 on 2021-07-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210720_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedloan',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approve', to='account.loanapplication'),
        ),
    ]
