# Generated by Django 3.2.4 on 2021-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_groupmemberinfo_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='member_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
