# Generated by Django 3.2.4 on 2021-07-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_approvedloan_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedloan',
            name='date_repaid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedloan',
            name='repaid',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repaid',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
