# Generated by Django 3.2.4 on 2021-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210720_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedloan',
            name='repaid_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
