# Generated by Django 3.2.4 on 2021-07-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_loanapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='application_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bm_date_action',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch_manager_approve',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch_manager_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='branch_manager_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_officer_approve',
            field=models.CharField(default='APPROVED', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='credit_officer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='senior_manager_approve',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='senior_manager_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='senior_manager_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='sm_date_action',
            field=models.DateField(blank=True, null=True),
        ),
    ]
