from django.urls import path, include
from . import views


urlpatterns = [
    path('', include('djoser.urls')),
    path('', include('djoser.urls.authtoken')),
    path('logged_in_user', views.logged_in_user),
    path('create_user', views.create_user),
    path('get_all_user', views.get_all_user),
    path('delete_user/<str:id>', views.delete_user),
    path('update_user', views.update_user),
    path('update_user_admin/<str:id>', views.update_user_admin),
    path('reset_password_otp', views.reset_password_otp),
    path('reset_password_confirm', views.reset_password_confirm),
    path('get_single_user/<str:id>', views.get_single_user),
    path('create_group', views.create_group),
    path('allgroup', views.get_all_group),
    path('addmember', views.add_member_to_group),
    path('allgroupmember', views.get_all_group_member),
    path('removegroup/<str:id>', views.remove_group),
    path('updategroup/<str:id>', views.update_group),
    path('removemember/<str:id>', views.remove_member),
    path('updatemember/<str:id>', views.update_member),
    path('get_group_member/<str:group_id>', views.get_group_member),
    path('groupbyid/<id>', views.get_single_group),
    path('getsinglemember/<str:id>', views.get_single_member),
    path('changeleader/<str:group_id>/<str:mobileNumber>', views.change_group_leader),
    path('admin_reset_password/<str:id>', views.admin_reset_password),
    path('oldloan/', views.oldCustomerBookLoan),
    path('newloan/', views.newCustomerBookLoan),
    path('all_loan/', views.allLoan),
    path('approveloan/<str:appId>', views.approveloan),
    path('repayloan/<str:appid>', views.repayloan),
    path('singleloan/<str:appid>', views.getSingleLoan),
    path('memberinfo/<str:id>', views.get_member_info),
    path('groupaction/<str:groupid>', views.groupAction),
    path('removeloan/<str:appid>', views.removeloan),
    # path('getallmembers/', views.getAllMember),
]
